
[font]
size = 12.0

[font.bold]
family = "HackGen"
style = "Bold"

[font.bold_italic]
family = "NimbusMono"
style = "Bold Italic"

[font.italic]
family = "NimbusMono"
style = "Italic"

[font.normal]
family = "HackGen"
style = "Regular"

[window]
opacity = 0.7

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
